<a href="https://colab.research.google.com/github/hvarS/NLPRefer/blob/main/WordEmbeddings_with_Keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
##Sentences 
sent = [
        "This is a great life",
        "I need water",
        "I am a coder"
]

In [3]:
sent

['This is a great life', 'I need water', 'I am a coder']

In [4]:
##Define vocabulary size from which we will extract the embeddings
vocab_size = 50000

###One hot representation of the sentences (kind of like Label Encoding in Tabular Data)

In [5]:
repr = [one_hot(sentence,vocab_size) for sentence in sent]

In [6]:
repr

[[14686, 18505, 14782, 12612, 45013],
 [7862, 3313, 37146],
 [7862, 32421, 14782, 9155]]

###Word Embedding Representation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential

In [8]:
import numpy as np

In [9]:
max_sent_length = max([len(s) for s in repr])

In [10]:
max_sent_length

5

In [11]:
padded_sentences = pad_sequences(repr,maxlen = max_sent_length,padding="post")

In [12]:
print(padded_sentences)

[[14686 18505 14782 12612 45013]
 [ 7862  3313 37146     0     0]
 [ 7862 32421 14782  9155     0]]


In [16]:
#Defining the embedding dimension
dims = 300

In [14]:
model = Sequential()


In [17]:
model.add(Embedding(vocab_size,dims,input_length=max_sent_length))
model.compile(optimizer="adam",loss = "mse")

In [18]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 5, 300)            15000000  
Total params: 15,000,000
Trainable params: 15,000,000
Non-trainable params: 0
_________________________________________________________________


In [26]:
embeddings = model.predict(padded_sentences)

In [28]:
type(embeddings)

numpy.ndarray

In [27]:
embeddings.shape

(3, 5, 300)

In [24]:
embeddings_direct = model(padded_sentences)

In [25]:
embeddings_direct.shape

TensorShape([3, 5, 300])